# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf5cc9e13633e383ff33c6656e814186e6b72e5d435b3da2be347adf231d563d4224e4215fc466dee2493b485643ded8f363ee5a05beac68d2d21b5e5a412b3

test:
  secret_key_base: 4eca7f7ef76eeea31ad3af527a80cd1366e40763cb9fff1892e909ab47b8a94de1c769f0421e121561dd37199617fb971368059e998c3e9f5cd628710e69d003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
